spring.application.name=recommendation-service

#postgres configuration
#spring.datasource.url=${POSTGRES_URL}
#spring.datasource.username=${POSTGRES_USERNAME}
#spring.datasource.password=${POSTGRES_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#neo4j configuration
spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}
spring.neo4j.database=${NEO4J_DATABASE}
spring.neo4j.instance.id=${NEO4J_INSTANCE_ID}
spring.neo4j.instance.name=${NEO4J_INSTANCE_NAME}